repos:
  - repo: local
    hooks:
    - id: generated-files
      name: Verifying generated files are uptodate
      entry: ./scripts/generated-files-uptodate.sh
      language: system
      require_serial: true
      pass_filenames: true
      stages: [pre-push, manual]
      files: '(openapi/.*|pkg/workers/worker_interface.go|pkg/client/ocm/id.go|pkg/client/aws/client.go|pkg/client/ocm/client.go|pkg/client/iam/client.go|pkg/services/authorization/authorization.go|pkg/services/sso/iam_service.go|pkg/client/redhatsso/client.go|pkg/auth/auth_agent_service.go|internal/central/pkg/services/cluster_placement_strategy.go|internal/central/pkg/services/cloud_providers.go|internal/central/pkg/services/clusters.go|internal/central/pkg/services/quota.go|internal/central/pkg/services/quota_service_factory.go|internal/central/pkg/clusters/cluster_builder.go|internal/central/pkg/clusters/provider.go|internal/central/pkg/services/central.go)'
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.8.0
    hooks:
      - id: golangci-lint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: end-of-file-fixer
        exclude: '^(?:secrets/db.*|internal/central/pkg/api/(admin|private|public)/.*|pkg/client/redhatsso/api/.*|emailsender/pkg/client/openapi/.*)$' # Matches either secrets/db.* files or the generated files under internal/central/pkg/api/(admin|private|public) and pkg/client/redhatsso/client/api.
      - id: check-json
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.5
    hooks:
      - id: shellcheck
        # Ignore scripts generated by openapi-generator.
        exclude: '^(?:internal/central/pkg/api/.*|pkg/client/redhatsso/api/.*|emailsender/pkg/client/openapi/.*)$'
  - repo: local
    hooks:
      - id: code/check
        name: make code/check
        entry: make code/check
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: actionlint
        name: lint GitHub Actions workflow files
        description: Runs actionlint to lint GitHub Actions workflow files
        entry: actionlint
        language: golang
        # This dependency can't be updated with 'pre-commit autoupdate'. Please bump it manually when necessary.
        additional_dependencies: [github.com/rhysd/actionlint/cmd/actionlint@v1.6.24]
        types: [ "yaml" ]
        files: "^.github/workflows/"
