## TODO disable operator installation when FSS runs with FEATURE_FLAG_UPGRADE_OPERATOR_ENABLED=true
{{- if .Values.acsOperator.enabled }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhacs-operator
  namespace: {{ .Release.Namespace }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhacs-operator
  namespace: {{ .Release.Namespace }}
spec:
  channel: latest
  installPlanApproval: Manual
  name: rhacs-operator
  source: {{ .Values.acsOperator.source }}
  sourceNamespace: {{ .Values.acsOperator.sourceNamespace }}
  startingCSV: rhacs-operator.{{ .Values.acsOperator.version }}
  config:
    resources:
      requests:
        cpu: 1
        memory: 200Mi
      limits:
        cpu: 2
        memory: 1Gi
---
{{- if .Values.acsOperator.upstream }}
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: {{ .Values.acsOperator.source }}
  namespace: openshift-marketplace
spec:
  displayName: 'RHACS Development'
  publisher: 'Red Hat ACS'
  sourceType: grpc
  image: quay.io/rhacs-eng/stackrox-operator-index:{{ .Values.acsOperator.version }}
---
{{- end }}
{{- end }}
