apiVersion: "operators.coreos.com/v1alpha1"
kind: Subscription
metadata:
  name: vertical-pod-autoscaler
  namespace: openshift-vertical-pod-autoscaler
spec:
  channel: stable
  installPlanApproval: Automatic
  name: vertical-pod-autoscaler
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  {{- if .Values.nodeSelector }}
  config:
    nodeSelector:
      {{- toYaml .Values.nodeSelector | nindent 6 }}
  {{- end }}
