# Default values for logging.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

groupPrefix: ""
aws:
  region: "us-east-1"
  accessKeyId: ""
  secretAccessKey: ""
