---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secrets-manager-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-access-keys
            key: access-key-id
            namespace: rhacs
          secretAccessKeySecretRef:
            name: aws-access-keys
            key: secret-access-key
            namespace: rhacs
