{{- if and (.Capabilities.APIVersions.Has "external-secrets.io/v1beta1") .Values.createExternalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: emailsender-db-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: {{ .Values.secretStore.aws.secretsManagerSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: emailsender-db
    creationPolicy: Owner
  data:
    - secretKey: db.user # pragma: allowlist secret
      remoteRef:
        key: "cluster-{{ .Values.clusterName }}-emailsender-db"
        property: "username"
    - secretKey: db.name # pragma: allowlist secret
      remoteRef:
        key: "cluster-{{ .Values.clusterName }}-emailsender-db"
        property: "databaseName"
    - secretKey: db.host # pragma: allowlist secret
      remoteRef:
        key: "cluster-{{ .Values.clusterName }}-emailsender-db"
        property: "host"
    - secretKey: db.password # pragma: allowlist secret
      remoteRef:
        key: "cluster-{{ .Values.clusterName }}-emailsender-db"
        property: "password" # pragma: allowlist secret
    - secretKey: db.port # pragma: allowlist secret
      remoteRef:
        key: "cluster-{{ .Values.clusterName }}-emailsender-db"
        property: "port"
{{- end }}
